languages:
   Ruby: true
   JavaScript: true
exclude_paths:
- "app/assets/javascripts/libs/*"
- "app/assets/stylesheets/libs/*"
- "public/assets/*"
- "db/cities/*"
- "db/migrate/*"
- "db/schema.rb"
- "vendor/*"
- "bin/*"
- "lib/tasks/cucumber.rake"
